### ISSUE TITLE
MVPArt 和MVPArms 这两个项目有什么区别？ 

### ISSUE THREAD

**Issue by colryzen** [JessYanCoding/MVPArt#10]
我看整个项目代码结构基本一致，只是减少基础库类的引用吗？对mvp 分层这些有区别吗，最近也在做代码重构，比较纠结MVVM 架构还是MVP 架构

**Comment by JessYanCoding** [comment]
MVPArt 和 MVPArms 区别只是在于，MVPArt 优化了 MVP 中 V 和 P 的通信，不需要写这么多接口方法，也不需要用 Dagger，其他诸如代码结构，网络，等地方两个框架都是一模一样的

**Comment by colryzen** [comment]
> MVPArt 和 MVPArms 区别只是在于，MVPArt 优化了 MVP 中 V 和 P 的通信，不需要写这么多接口方法，也不需要用 Dagger，其他诸如代码结构，网络，等地方两个框架都是一模一样的

好的，了解了，谢谢回复。
两个项目中的框架部分核心代码 ，所有的pull requests 都会同步的是吗？

**Comment by JessYanCoding** [comment]
对的，我现在公司的核心组件化项目使用的就是 MVPArt，而且是远程依赖，所以在持续维护上，这点不用担心，两个框架都会同步发布新版本，版本更新内容都会相同，同步 pull requests 不做保证，时间充裕就会同步 pull requests，时间不充裕，会在发布版本前将 MVPArms 更新的所有内容一次性更新到 MVPArt

MVPArt 和 MVPArms 与 MVP 相关的代码相比整个框架其实是非常少的，百分 5 不到，其他百分 95 都是关于架构上的核心功能，这点你如果看了源码就应该知道，现在一直维护的都是这部分核心功能，这部分相当于就是 MVP 的底层架构，MVPArt 和 MVPArms 都可以共用这里的代码，关于 MVP 的内容经过两年的更新已经稳定，所以 MVP，MVC，MVVM 对我来说都不重要，我只要花少量时间就可以把 MVPArms 或 MVPArt 改成 MVVM，只是这部分核心代码我没有完全和 MVP 隔离开，维护上需要些许精力，所以不想在同时维护一个 MVVM 库，后面可能会考虑将这部分独立

**Comment by colryzen** [comment]
我们公司最近在重构框架代码，我们可能会基于MVPArt的基础上改造，MVPArt和MVPArms 是个很好的框架，感谢作者的无私开源，也再次感谢，作者非常认真的回答我的问题，谢谢。
