### ISSUE TITLE
可以用androidx吗，直接点迁移？

### ISSUE THREAD

**Issue by helloworld10010** [JessYanCoding/MVPArt#13]

**Comment by helloworld10010** [comment]
脑子有点糊，我新项目用androidx，这demo中我看fragment相关代码里检测的是v4fragment

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/XeJQrwbxKk6JbBn8C3fqKg

**Comment by helloworld10010** [comment]
> https://mp.weixin.qq.com/s/XeJQrwbxKk6JbBn8C3fqKg

谢谢
