### ISSUE TITLE
大佬，这个库没有维护了吗

### ISSUE THREAD

**Issue by bux-git** [JessYanCoding/MVPArt#15]

**Comment by JessYanCoding** [comment]
最近工作和生活中有很多自己的事情要做，很忙，所有库都没有提交新的代码，只是偶尔解决 issues 和 pr

**Comment by bux-git** [comment]
大神幸苦，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JessYan"<notifications@github.com&gt;; 
发送时间: 2019年10月29日(星期二) 下午3:09
收件人: "JessYanCoding/MVPArt"<MVPArt@noreply.github.com&gt;; 
抄送: "不修"<471025316@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JessYanCoding/MVPArt] 大佬，这个库没有维护了吗 (#15)




最近工作和生活中有很多自己的事情要做，很忙，所有库都没有提交新的代码，只是偶尔解决 issues 和 pr
