### ISSUE TITLE
Presenter中的EventBus事件如何回调到View层级去？

### ISSUE THREAD

**Issue by h3clikejava** [JessYanCoding/MVPArt#2]
EventBus的事件没有View的Message对象，如何对View进行操作？

**Comment by h3clikejava** [comment]
好吧...这个库的设计就是Presenter中没有Message就没法传递事件到View中的...所以要在View里面实现EventBus注册....哎

**Comment by JessYanCoding** [comment]
是的,view既是事件发送者也是事件处理者
