### ISSUE TITLE
完全是为了设计而编码

### ISSUE THREAD

**Issue by liupeng110** [JessYanCoding/MVPArt#3]
你有没有想过mvc甚至vc更是一种分布式的编程思想？
mvp平白无故增加了代码复杂度 阅读难度 一个中等的项目用mvp就会非常繁杂更不用说大型项目
小的项目根本无需引入这样一个 完全是为了设计而编码的东西

**Comment by JessYanCoding** [comment]
小项目始终会变大,等项目一大,如果开始没规划好所有职责,扩展维护就会非常不方便,你觉得项目使用mvp会让代码更复杂没有其他优点,只是你没有认识到他带来的好处,所以说再多也没用,只有实践才出真理,更何况google也早出了mvp的规范,说明google也鼓励使用mvp,考虑事情的角度不一样,那观点自然不一样,你觉得mvp一无是处,不用也罢

**Comment by liupeng110** [comment]
讨论一下优缺点而已，分布式编程思想你用过么

**Comment by JessYanCoding** [comment]
分布式没用过,项目组件化,模块化到用过

**Comment by JerryMissTom** [comment]
使用MVP的好处是显而易见的，虽然文件数和代码量上去了，但是逻辑清晰，下一个接手的人也能很快进行维护和拓展，所谓的阅读难度，实在是不敢苟同。

**Comment by liupeng110** [comment]
文件数上去了,代码量上去  必然就会增加复杂度    耦合度另说       
因为mvp比mvc多了一个抽象层  复杂度从O的平方 变成O的3次方    
单就你一个逻辑的mvp一大坨  维护起来就很费劲了 更不用说逻辑多的情况

**Comment by liupeng110** [comment]
有没有办法取其精华，弃其糟粕            找出一种更好的模式

**Comment by JerryMissTom** [comment]
MVC的缺点也是显而易见，整个View承载的东西太多了，一个Activity和Fragment代码就看不过来，梳理逻辑起来很费劲。按照你的说法，MVVM模式也是不可取的，其也多了中间层，代码量也上去了，但是在某些场景下，好处不是一点点。另外没听说过对业务分层复杂度的计算方法是由层数的n次方处理的。事实上代码量小又逻辑清晰的项目真的是很难做到。

**Comment by liupeng110** [comment]
mvp把复杂的逻辑处理转移到Presneter  这个思想很好 ，但是又引入interface层
好像是滥用interface一样，多个interface和回调 会造成很多不必要的麻烦     对代码的可读性造成一些影响

mvvm相对mvp有过之而无不及
一:数据绑定使得 Bug 很难被调试。你看到界面异常了，有可能是你 View 的代码有 Bug，也可能是 Model 的代码有问题。数据绑定使得一个位置的 Bug 被快速传递到别的位置，要定位原始出问题的地方就变得不那么容易了。
二：对于过大的项目，数据绑定需要花费更多的内存。

**Comment by liupeng110** [comment]
我感觉善用一些开源框架，和一些util工具类  
把代码量相对变小，逻辑相对变清晰 还是可以做到的

**Comment by liupeng110** [comment]
理想的状态 代码是顺序执行的 逻辑也是顺序执行的   
以网络请求为例  eg：注册页面
1.在异步任务里进行同步请求  得到请求结果                                                        
2.拿到str字符串之后  用个自己封装的jsonUtil解析成Bean 或者List<Bean>    
3.切换线程之后  刷新ui   

出现问题在1和2后面插 两个log就能准确定位bug出现在哪里

**Comment by JerryMissTom** [comment]
我们使用MVP等模式的同时并不排斥第三方框架的使用，同时也会斟酌情况进行使用，一个实践MVP的项目不代表每个界面都使用MVP来处理，没那么死板。你说MVP的滥用带来调试Bug的困难，但是你没看到分层带来的测试的方便，分别写View和Presenter，分别测试，独立而高效。

**Comment by liupeng110** [comment]
1.如果可以尽可能统一 一种风格  
你这里用一下mvp那里用一下mvc  如果再用下mvvm   不是挖了另一种坑？
2.你应该用过单元测试，绝大多数测试需求都能满足  
3.总结以上  感觉有点得不偿失

**Comment by liupeng110** [comment]
能上代码描述下么  伪代码   或者主要步骤也可以

**Comment by RockyQu** [comment]
MVP的流行肯定也是有一定道理的，解决了很多问题，比如测试，复用性，耦合度，Google官方都给出了很多示例，关于复杂度这个MVPArt已经很好的解决了大部分问题，V,P,M都只继承Base就行了，如果这个还叫复杂那啥叫简单？随便举个例子，两个List UI相同的页面，但通过不同的接口加载不同的List，这时候就可以复用P，难到你要都写在 V 里？
