### ISSUE TITLE
权限拒绝会出现崩溃现象，msg中IView为空

### ISSUE THREAD

**Issue by tokiii** [JessYanCoding/MVPArt#6]
`Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void me.jessyan.art.mvp.IView.showMessage(java.lang.String)' on a null object reference
                                                                            at me.jessyan.mvpart.demo.mvp.presenter.UserPresenter$1.onRequestPermissionFailureWithAskNeverAgain(UserPresenter.java:94)
                                                                            at me.jessyan.art.utils.PermissionUtil$1.onNext(PermissionUtil.java:98)
                                                                            at me.jessyan.art.utils.PermissionUtil$1.onNext(PermissionUtil.java:87)`

**Comment by JessYanCoding** [comment]
Demo ?

**Comment by JessYanCoding** [comment]
解决了？

**Comment by tokiii** [comment]
你那没复现的话，我自己查查原因是不是我的问题。

**Comment by JessYanCoding** [comment]
好的

**Comment by tokiii** [comment]
问题是我这确实能复现，但是改变了下代码就好了，算是解决问题，但是不明白这个问题为啥出现，对java基础了解比较浅，修改代码如下：
<pre> public void requestUsers(final Message msg) {
        final boolean pullToRefresh = (boolean) msg.objs[0];
        IView iView = msg.getTarget();
        PermissionUtil.externalStorage(new PermissionUtil.RequestPermission() {
            @Override
            public void onRequestPermissionSuccess() {
                //request permission success, do something.
            }
            @Override
            public void onRequestPermissionFailure(List<String> permissions) {
                iView.showMessage("Request permissions failure");
            }
            @Override
            public void onRequestPermissionFailureWithAskNeverAgain(List<String> permissions) {
                iView.showMessage("Need to go to the settings");
            }
        }, mRxPermissions, mErrorHandler);</pre>

**Comment by JessYanCoding** [comment]
当用户拒绝的时候, msg.target 已经被释放并置为 null, 所以回调接口会报空指针, 你在 msg.target 被置
为 null 之前, 用一个局部变量持有后自然就不存在这个问题了

**Comment by tokiii** [comment]
主要是不是每次拒绝都会复现，有的时候也不为空....

**Comment by JessYanCoding** [comment]
很正常，因为请求网络结束后会释放 msg 的所有资源, 如果请求网络前权限请求被拒绝，这时 showMessage 就不会出现空指针, 如果在请求网络之后就会, 因为你不能百分百保证谁在前谁在后，所以肯定不会百分百复现

**Comment by tokiii** [comment]
明白了，多谢大神解答！！
