### ISSUE TITLE
在Demo中开启混淆后UserPresenter报错

### ISSUE THREAD

**Issue by RockyQu** [JessYanCoding/MVPArt#8]
super(appComponent.repositoryManager().createRepository(UserRepository.class));  这句报错，请问有遇到的吗？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki#1.5  说得很清楚, 需要自己去定义混淆规则

**Comment by RockyQu** [comment]
原因找到了，因为底层 RepositoryManager 里的 findConstructorForClass 方法用的是反射，不能混淆 UserRepository 这个类
可以添加混淆参数
-keep class * implements me.jessyan.mvpart.demo.mvp.IModel {
    <methods>;
    <fields>;
}
直接拿来用的，不看底层源码的，肯定会有这个问题，建议记录下来

**Comment by JessYanCoding** [comment]
ok, 感谢指正, 已更新到 **proguard-rules.pro**
