### ISSUE TITLE
请问DefaultAdapter<T>是怎么来更新适配器

### ISSUE THREAD

**Issue by quguangle** [JessYanCoding/MVPArt#9]
我看了你所有的源码，看见你框架中使用默认的适配器，但是你适配器中兵没有增查改等操作，而且你的数据也是通过构造器传进去的。如果此时我想移除适配器中的某条数据或者是像适配器中添加某个特定位置的数据，你这边都没法操作适配器。

**Comment by quguangle** [comment]
在而且看见你用的模板，完全没有体现出重用presenter,你每对应一个界面也分别对应了p,m,v，无非你这里只是减少了p,v层的接口，p,v采用了Message来负责通信，Message中持有view层的引用。但是还是没有看出来有多大的改善啊。

**Comment by quguangle** [comment]
在就是如果一个recyclerView,item中有多个view触发不同的事件，而这些事件都是要与服务器交互的，此时我们需要把这些事件通过接口的形式放在activity或者fragment中处理，而你的框架处理数据全部放在BaseHolder<T>的子类，那这边是怎么去处理这些情况呢。

**Comment by JessYanCoding** [comment]
1. 看了你得第一个问题，我想你可能是不会用 Recyclerview, 对数据进行增删改查，是对数据源进行处理，而不是对 Adapter 进行处理，数据源是传进Adapter 的 List, 外部已经持有 List ，对它进行增删改查后，通知 Adapter 数据变更即可，这个问题太基础就不过多回答了

2. 模板默认是一个完整的mvp模式，肯定是没涉及到重用的，只是让基础代码快速生成，至于进阶的重用Presenter, 需要自己去做，原因很简单，我怎么知道你要重用几个 Presenter ,而且每个 presenter 名字也不一样，我怎么知道你要怎么命名

3. Item设置监听器，Item 点击后执行对应逻辑，而且 BaseHolder 中也可以访问网络，通过 AppComponent 就能拿到 RepositoryManager ，这个问题的方式太多

**Comment by quguangle** [comment]
谢谢解答，第一遍读代码，理解不是太清晰。

**Comment by JessYanCoding** [comment]
你说的 MVPArt 对 MVP 模式是否有改善这个问题，我在 [这篇文章](https://juejin.im/post/58b25e588d6d810057ed3659) 已经写的够清楚了，这也是使用 MVP 两年的总结，我为什么会在 [MVPArms](https://github.com/JessYanCoding/MVPArms) 之上还推出了这个库，肯定是有道理的，如果你还是理解不了那篇文章，那我也不想过多解释了，仁者见仁智者见智

**Comment by quguangle** [comment]
嗯！思路挺好的，我现在面临问题就是你这篇文章所提的, 可能是我们用于实战，只是把你代码仔细的看了一遍，思路很清晰。

**Comment by quguangle** [comment]
没有用于实战，不知道框架的强大，代码写的详细，注释也非常清晰。这是我看的开源代码最容易看的

**Comment by quguangle** [comment]
非常感谢

**Comment by quguangle** [comment]
有个问题，你这框架里采用的鸿阳的适配方式。请问有在现在的项目中使用吗？他这种方式在某些机型上还是有一些问题的，不知道你碰到没有。

**Comment by quguangle** [comment]
今日头条推出了一种适配方式，不知你否了解。

**Comment by JessYanCoding** [comment]
我是一直在使用，框架也允许你不使用，这个库使用两年了暂时没遇到什么问题，不过有问题是很正常的，没有一个适配方案，能保证百分百适配所有机型，但他至少能帮你解决大部分机型的适配，并且根据设计图填写尺寸，这也是对于设计图以苹果尺寸为准的开发项目是个神器

**Comment by JessYanCoding** [comment]
今日头条那个就是根据去年一个人推出的方案优化的，去年就看了源码，新的方案，很多未知问题，没有想象中美好，鸿洋的方案在市场上检验了4年，有问题也是已知问题，并且这个方案对老项目有影响

**Comment by quguangle** [comment]
他这个方案只适合新项目，我觉得你这个框架很适合我们外包公司，拿到项目马上就可以写了，但是前提是要把你的源码搞清楚

**Comment by JessYanCoding** [comment]
是的，我群里面用我这个框架写过 3 个项目以上的多的是，特别熟练过后，整个安卓组都会用，效率和质量都有提升，我这个框架也是为了中小企业而生，有什么问题可以在 qq群 里沟通，群号：301733278

**Comment by quguangle** [comment]
你这边使用AutoLayout方式适配，是你这边已经处理过很多问题了吧，我看见你的demno上使用recyclerview时候，已经没有使用原来的方式还要去计算item

**Comment by quguangle** [comment]
我熟悉玩之后，打算用原来的老项目，用你的框架方式来改建一下。

**Comment by quguangle** [comment]
也使用你这种方式来适配，到时候写好之后可以追加到你的项目事例中

**Comment by JessYanCoding** [comment]
可以
